# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger: none

pr:
  branches:
    include:
      - development

name: $(Rev:r)

pool:
  vmImage: 'macos-latest'

steps:
- script: |
      ./gradlew ktlint

- task: CopyFiles@2
  condition: failed()
  inputs:
    contents: '**/ktlint/*.html'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  condition: failed()
  inputs:
    PathtoPublish: '$(build.artifactStagingDirectory)'
    ArtifactName: 'KlintReport'
    publishLocation: 'Container'

- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx4608m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
